baseURL = '/'
languageCode = 'en-au'
title = 'namnd ☕'
theme = 'ezhil'
googleAnalytics = "G-8LL0B59QRS"
summaryLength = 20

copyright = "© Copyright namnd.com"
[author]
  name = 'Nam Nguyen'

[params]
  mainSections = ["posts"]
  subtitle = "personal blog"

[[menu.main]]
  name = 'Posts'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 2


[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/namnd"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/fishsauc3"

[[params.social]]
  name = "RSS"
  icon = "rss"
  url = "/index.xml"
