baseURL = '/'
languageCode = 'en-us'
title = 'namnd ☕'
theme = 'ezhil'
copyright = "© Copyright namnd.com"
summaryLength = 20

googleAnalytics = "G-641B0H8SCC"

[params]
  mainSections = ["posts"]
  subtitle = "personal blog"

[[menu.main]]
  name = 'Posts'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 2


[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/namnd"

  [[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/fishsauc3"


