baseURL = '/'
languageCode = 'en-au'
title = 'namnd ☕'
theme = 'ezhil'
googleAnalytics = "G-8LL0B59QRS"
summaryLength = 20

copyright = "© Copyright namnd.com"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[author]
  name = 'Nam Nguyen'

[params]
  mainSections = ["posts"]
  subtitle = "personal blog"

[[menu.main]]
  name = 'Posts'
  url = '/'
  weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 3

[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/namnd"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/namnd_"

[[params.social]]
  name = "RSS"
  icon = "rss"
  url = "/index.xml"

# Enable tags.
[taxonomies]
   tag = "tags"
